### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by petrichbg** [Fenrirthviti/stream-site#28] opened 2017-05-02 14:51 UTC
pg_query_params(): Query failed: ERROR: inconsistent types deduced for parameter $7 LINE 1: ...ffline_image) VALUES ($1, $2, $7, 0, $3, $4, $5, $6, $7, $8) ^ DETAIL: text versus boolean in /var/www/html/lib/user.class.php on line 165

how to fix this ?

**Comment by Fenrirthviti** [comment] 2017-05-02 14:54
What page is triggering this error?

Did you add the appropriate columns to the database for offline image, with the default values?

**Comment by Fenrirthviti** [comment] 2017-05-02 15:16
Disregard, I see the issue is during registration. Stand by, investigating.

**Comment by Fenrirthviti** [comment] 2017-05-02 15:23
This is fixed in https://github.com/Fenrirthviti/stream-site/commit/3ea4de2940abfe979ba6b17627ae5f8e90562d80

Please check and confirm.

**Comment by petrichbg** [comment] 2017-05-02 15:33
;) good now work can registrer new acc 👍

**Comment by Fenrirthviti** [comment] 2017-05-02 16:06
Thank you for the report, was a miss on my part!

**Closed as completed by Fenrirthviti** 2017-05-02 16:06 UTC
